/**
 * @nova/database migration runner using drizzle-orm.
 *
 * Reads the drizzle schema and applies pending migrations from the
 * ./drizzle directory generated by drizzle-kit.
 */
import 'dotenv/config';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';

const DATABASE_URL = process.env.DATABASE_URL;

if (!DATABASE_URL) {
 console.error('[migrate] DATABASE_URL is not set');
 process.exit(1);
}

async function main() {
 console.log(`[migrate] Connecting to ${DATABASE_URL.replace(/\/\/.*@/, '//***@')}`);
 const sql = postgres(DATABASE_URL, { max: 1 });
 const db = drizzle(sql);

 try {
 console.log('[migrate] Applying pending migrations...');
 await migrate(db, { migrationsFolder: './drizzle' });
 console.log('[migrate] All pending migrations applied successfully');
 } catch (err) {
 console.error('[migrate] Failed:', err);
 process.exit(1);
 } finally {
 await sql.end();
 }
}

main();
