platform :ios, '13.0'
use_frameworks!
use_modular_headers!

# Flutter pods
flutter_application_path = File.expand_path('..', __dir__)
load File.join(flutter_application_path, 'Flutter', 'podhelper.rb')

target 'Runner' do
 use_frameworks!
 use_modular_headers!

 flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
 flutter_additional_ios_build_settings(target)
 target.build_configurations.each do |config|
 config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
 config.build_settings['ENABLE_BITCODE'] = 'NO'
 end
 end
end
