#!/bin/bash
# NOVA Production Deployment Script
# Provisions and deploys the complete production stack to AWS
#
# Usage:
# ./deploy.sh [--plan-only]
# ./deploy.sh [--skip-terraform]
# ./deploy.sh [--skip-docker]
# ./deploy.sh [--skip-nginx]
# ./deploy.sh [--skip-ssl]
#
# Prerequisites:
# - Terraform >= 1.6.0
# - AWS CLI configured
# - SSH key pair created in AWS
# - Domain DNS pointed to ALB or EC2 IP

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
INFRA_DIR="${PROJECT_ROOT}/infrastructure/terraform"
NGINX_DIR="${PROJECT_ROOT}/infrastructure/nginx"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SKIP_TERRAFORM=false
SKIP_DOCKER=false
SKIP_NGINX=false
SKIP_SSL=false

# Parse arguments
while [[ $# -gt 0 ]]; do
 case $1 in
 --plan-only) PLAN_ONLY=true; shift ;;
 --skip-terraform) SKIP_TERRAFORM=true; shift ;;
 --skip-docker) SKIP_DOCKER=true; shift ;;
 --skip-nginx) SKIP_NGINX=true; shift ;;
 --skip-ssl) SKIP_SSL=true; shift ;;
 *) echo "Unknown option: $1"; exit 1 ;;
 esac
done

log_info() {
 echo -e "${BLUE}[deploy]${NC} $1"
}

log_success() {
 echo -e "${GREEN}[deploy]${NC} $1"
}

log_warning() {
 echo -e "${YELLOW}[deploy]${NC} $1"
}

log_error() {
 echo -e "${RED}[deploy]${NC} $1"
}

# =============================================
# Step 1: Provision Infrastructure (Terraform)
# =============================================
deploy_infrastructure() {
 log_info "=== Step 1: Provisioning AWS Infrastructure ==="

 cd "$INFRA_DIR"

 if [[ ! -f "terraform.tfvars" ]]; then
 log_warning "terraform.tfvars not found. Copying from example..."
 cp terraform.tfvars.example terraform.tfvars
 echo ""
 echo "IMPORTANT: Edit terraform.tfvars with your production values before running:"
 echo " - key_pair_name: Your EC2 SSH key pair"
 echo " - ssl_certificate_arn: ACM certificate ARN"
 echo " - allowed_ssh_cidr: Your IP CIDR for SSH access"
 echo ""
 read -p "Press Enter to continue or Ctrl+C to abort..."
 fi

 log_info "Initializing Terraform..."
 terraform init -upgrade

 log_info "Planning infrastructure changes..."
 terraform plan -out=tfplan -var-file="terraform.tfvars"

 if [[ "${PLAN_ONLY:-false}" == "true" ]]; then
 log_info "Plan-only mode. Review tfplan above."
 return 0
 fi

 log_info "Applying infrastructure changes..."
 log_warning "This will create AWS resources that incur costs. Proceeding..."
 terraform apply tfplan

 log_success "Infrastructure provisioned."
 echo ""
 echo "Outputs:"
 terraform output

 # Export outputs for later steps
 export ALB_DNS=$(terraform output -raw load_balancer_dns 2>/dev/null || echo "")
 export EC2_IP=$(terraform output -raw ec2_public_ip 2>/dev/null || echo "")
 export RDS_ENDPOINT=$(terraform output -raw rds_endpoint 2>/dev/null || echo "")
 export REDIS_ENDPOINT=$(terraform output -raw redis_endpoint 2>/dev/null || echo "")
 export S3_BUCKET=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "")

 log_success "Infrastructure outputs captured."
}

# =============================================
# Step 2: Deploy Application (Docker Compose)
# =============================================
deploy_application() {
 log_info "=== Step 2: Deploying Application to EC2 ==="

 if [[ -z "${EC2_IP:-}" ]]; then
 log_error "EC2 IP not set. Run terraform apply first."
 return 1
 fi

 # Read secrets from Terraform outputs
 DB_PASSWORD=$(cd "$INFRA_DIR" && terraform output -raw db_password 2>/dev/null || echo "")
 REDIS_PASSWORD=$(cd "$INFRA_DIR" && terraform output -raw redis_password 2>/dev/null || echo "")

 log_info "Connecting to EC2 instance at ${EC2_IP}..."

 # Create production .env
 ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 ec2-user@"${EC2_IP}" "
 mkdir -p /opt/nova/infrastructure/backups/postgres
 " 2>/dev/null || {
 log_error "Cannot connect to EC2 instance. Verify SSH key and security group."
 return 1
}

 log_info "Creating production environment file..."
 ssh ec2-user@"${EC2_IP}" "cat > /opt/nova/.env.production << ENVEOF
# =============================================
# NOVA — Production Environment
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# =============================================

NODE_ENV=production
APP_URL=https://nova.leadup.in

# Database
POSTGRES_USER=nova_app
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=nova
DATABASE_URL=postgres://nova_app:${DB_PASSWORD}@${RDS_ENDPOINT}:5432/nova

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@${REDIS_ENDPOINT}:6379

# S3
S3_ENDPOINT=s3.amazonaws.com
S3_ACCESS_KEY=
S3_SECRET_KEY=
S3_BUCKET=${S3_BUCKET:-nova-leadup-assets-production}

# Auth
JWT_SECRET=\$(openssl rand -base64 64)
REFRESH_TOKEN_SECRET=\$(openssl rand -base64 64)
AUTH_ENCRYPTION_KEY=\$(openssl rand -base64 32)
API_KEY_SECRET=\$(openssl rand -base64 64)
JWT_EXPIRES_IN=15m
CORS_ORIGIN=https://nova.leadup.in,https://admin.nova.leadup.in

# Monitoring
LOG_LEVEL=warn

# AI (configure when available)
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
# ELEVENLABS_API_KEY=
# WHISPER_API_KEY=
ENVEOF
" 2>/dev/null

 log_success "Environment file created on EC2."
}

# =============================================
# Step 3: Deploy nginx
# =============================================
deploy_nginx() {
 log_info "=== Step 3: Deploying nginx ==="

 if [[ -z "${EC2_IP:-}" ]]; then
 log_error "EC2 IP not set. Run terraform apply first."
 return 1
 fi

 log_info "Installing and configuring nginx on EC2..."
 ssh ec2-user@"${EC2_IP}" "
 sudo dnf install -y nginx || sudo yum install -y nginx
 sudo mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled
 " 2>/dev/null

 log_info "Uploading nginx configuration..."
 scp "${NGINX_DIR}/default.conf" ec2-user@"${EC2_IP}":/tmp/nova-nginx.conf 2>/dev/null
 ssh ec2-user@"${EC2_IP}" "
 sudo mv /tmp/nova-nginx.conf /etc/nginx/sites-available/nova.conf
 sudo ln -sf /etc/nginx/sites-available/nova.conf /etc/nginx/sites-enabled/default
 sudo nginx -t
 " 2>/dev/null

 log_success "nginx configuration deployed."
}

# =============================================
# Step 4: SSL Certificate Setup
# =============================================
setup_ssl() {
 log_info "=== Step 4: Setting up SSL Certificate ==="

 if [[ -z "${EC2_IP:-}" ]]; then
 log_error "EC2 IP not set. Run terraform apply first."
 return 1
 fi

 log_info "Running certbot for SSL..."
 log_warning "Ensure DNS for nova.leadup.in points to ${EC2_IP} or ALB DNS before continuing."

 ssh ec2-user@"${EC2_IP}" "
 bash /tmp/ssl-setup.sh
 " 2>/dev/null || log_warning "SSL setup may have failed — check certbot logs on EC2."

 log_success "SSL setup complete."
}

# =============================================
# Step 5: Build and Deploy Docker Images
# =============================================
deploy_docker() {
 log_info "=== Step 5: Deploying Docker Compose ==="

 if [[ -z "${EC2_IP:-}" ]]; then
 log_error "EC2 IP not set. Run terraform apply first."
 return 1
 fi

 log_info "Building and starting services on EC2..."
 ssh ec2-user@"${EC2_IP}" "
 cd /opt/nova

 # Ensure docker-compose.prod.yml is present
 # (To be copied from repo during code deployment)

 echo 'docker-compose.prod.yml must be deployed to /opt/nova before this step'
 echo 'Run: scp docker-compose.prod.yml ec2-user@${EC2_IP}:/opt/nova/'
 " 2>/dev/null

 log_warning "Docker deployment requires the repository to be cloned on EC2."
 log_info "Clone repo first:"
 log_info " ssh ec2-user@${EC2_IP}"
 log_info " git clone https://github.com/leadupofficial/nova-leadup.git /opt/nova"
 log_info " cd /opt/nova"
 log_info " docker compose -f docker-compose.prod.yml up -d"
}

# =============================================
# Step 6: Verification
# =============================================
verify_deployment() {
 log_info "=== Step 6: Verifying Deployment ==="

 if [[ -z "${EC2_IP:-}" && -z "${ALB_DNS:-}" ]]; then
 log_error "No IP/DNS available. Run terraform apply first."
 return 1
 fi

 CHECK_HOST="${ALB_DNS:-$EC2_IP}"
 CHECK_URL="http://${CHECK_HOST}"

 log_info "Checking services at ${CHECK_URL}..."

 # Check nginx
 log_info "Checking nginx..."
 curl -s -o /dev/null -w "%{http_code}" "${CHECK_URL}/health/live" 2>/dev/null | grep -q "200" && \
 log_success "nginx is responding" || log_warning "nginx not responding yet"

 # Check API
 log_info "Checking API..."
 curl -s -o /dev/null -w "%{http_code}" "${CHECK_URL}/health/ready" 2>/dev/null | grep -q "200" && \
 log_success "API is healthy" || log_warning "API not ready yet"

 log_info "Deployment verification complete."
 echo ""
 echo "Next steps:"
 echo " 1. Run database migrations: docker compose -f docker-compose.prod.yml exec api pnpm run db:migrate"
 echo " 2. Seed initial data: docker compose -f docker-compose.prod.yml exec api pnpm run db:seed"
 echo " 3. Configure monitoring dashboards"
 echo " 4. Set up automated backup cron job"
 echo " 5. Run full smoke tests against https://nova.leadup.in"
}

# =============================================
# Main
# =============================================
main() {
 echo ""
 log_info "=========================================="
 log_info " NOVA Production Deployment"
 log_info " Project: Nova Leadup"
 log_info " Domain: nova.leadup.in"
 log_info "=========================================="
 echo ""

 if [[ "${SKIP_TERRAFORM}" == "false" ]]; then
 deploy_infrastructure
 echo ""
 fi

 if [[ "${SKIP_NGINX}" == "false" && "${SKIP_TERRAFORM}" == "false" ]]; then
 deploy_nginx
 echo ""
 fi

 if [[ "${SKIP_DOCKER}" == "false" ]]; then
 deploy_docker
 echo ""
 fi

 if [[ "${SKIP_SSL}" == "false" ]]; then
 setup_ssl
 echo ""
 fi

 verify_deployment
 echo ""

 log_success "=========================================="
 log_success " Deployment complete!"
 log_success "=========================================="
}

main "$@"
