# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users: Gradle settings configured through the IDE
# will override any settings specified in this file.
# For more details visit http://www.gradle.org/docs/current/userguide/build_environment.html

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
